name: Documentation

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt

      - name: Install Sphinx
        run: pip install Sphinx

      - name: Generate Sphinx HTML documentation
        run: |
          cd docs/
          make html

      - name: Generate test report
        run: pytest --html=docs/build/html/tests.html --self-contained-html || true

      - name: Install GitHub visualizations to output directory
        run: |
          cp -r github-vis/ docs/build/html/
          rm docs/build/html/github-vis/.gitignore

          # use minified vue.js
          sed -i 's:vue/dist/vue.js:vue@2.6.10:g' docs/build/html/github-vis/index.html
          # install github token (it's read-only but still not great)
          echo "const GRAPHQL_TOKEN = '${{ secrets.GRAPHQL_TOKEN }}';" > docs/build/html/github-vis/token.js

      - name: Deploy documentation and test report to GitHub pages
        uses: peaceiris/actions-gh-pages@v2.5.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./docs/build/html
